### ISSUE TITLE
Request to be added to cdnjs distribution platform

### ISSUE THREAD

**Issue by robojamison** [kylefox/jquery-tablesort#15]
[cdnjs](https://cdnjs.com) is a distribution platform for small-ish JavaScript libraries that don't have the budget/traffic to pay for a huge CDN or don't care to. You can request to be added to their CDN by [opening an issue](https://github.com/cdnjs/cdnjs/issues/new?title=[Request]%20Add%20tablesort%20) on their repo.

I'm using your library in a production application and I'd rather use some else's CDN to host it than to host it locally, both to avoid disk I/O slowdowns and because we're currently using a CDN for every other script and stylesheet we load. I think you benefit from this, so I hope you'll consider it!

**Comment by kylefox** [comment]
Good suggestion, I'll try to find some time to put together the package + other requirements they want.

**Comment by kylefox** [comment]
@robojamison Realistically I'm not going to get a chance to do this (create the package, tests, etc). If you submit a pull-request that meets their requirements I'm happy to re-open and merge.
