### ISSUE TITLE
How to specify default sort column and direction

### ISSUE THREAD

**Issue by connercowling** [kylefox/jquery-tablesort#17]
From the readme:
```
// Sorts by the specified column and, optionally, direction ('asc' or 'desc').
// If direction is omitted, the reverse of the current direction is used.
tablesort.sort(th, direction);
```

I take this to mean I should be able call `tablesort.sort(th, direction)` after creating my table in order to have a given `th` sorted on page load.  It's not working however.  

I've tried:
  - `tablesort.sort(<th-node>, 'asc')`
  - `tablesort.sort(<id-of-th>, 'asc')`
  - Setting the `tablesort.$th`, `tablesort.index`, and `tablesort.direction`

Results in:
`Uncaught TypeError: b.index is not a function`

Thanks in advance

**Comment by janniconl** [comment]
@connercowling Did you manage to make this work? Struggling with the same issue.

**Comment by connercowling** [comment]
@janniconl No. Please let me know if you figure it out.  I'll do the same!

**Comment by kylefox** [comment]
@connercowling @janniconl Can you post a [CodePen](http://codepen.io/pen/) (or similar) demonstrating the problem?

When I add the code below to the demo, the table is sorted when the page loads:

```javascript
$(function() {
	$('#table').tablesort().data('tablesort').sort($("#th"));
});
```

(Assumes you have `<table id="table">` and the column to sort by is `<th id="th">`)

**Comment by janniconl** [comment]
@kylefox Thx for your reply mate. Your example works for me too. I guess I was struggling with the right way to adress the plugin and a bit confused by the example in the readme. Anyways for me it all works now, thanks again! This default sorting might be useful for others to add to the readme/documentation. I'm sure @connercowling can make this work now aswell. Cheers

**Comment by kylefox** [comment]
Good call, added it to the [README](https://github.com/kylefox/jquery-tablesort#default-sorting).
