### ISSUE TITLE
sort order when clicking on a different column

### ISSUE THREAD

**Issue by quape** [kylefox/jquery-tablesort#20]
Hi there,

nice plugin! The sort order should always be ascending (or default one for that column) when clicking on a column which is not the current one. At the moment sort order changes with each click. This should of course only be the case when clicking on the current column. As it is now it's quite confusing ;)

**Comment by kylefox** [comment]
Sounds reasonable — I don't have time to implement this myself, but if you send a pull request I'll be happy to consider it :)

**Comment by kylefox** [comment]
Fixed in #25
