### ISSUE TITLE
&#8203; being injected into my data-sort-value

### ISSUE THREAD

**Issue by SoLoGHoST** [kylefox/jquery-tablesort#21]
Clicking on column once shows correct order, but injects `&#8203;` in front of my data-sort-value attribute strings randomly on some td elements, but not all.  Therefore further sorting on that column, shows wrong order since it injects `&#8203;` in front of the actual value.

I am using UTF-8 charset, and not sure what could be causing this.  This seems like a bug with the plugin since this only happens when clicking on the sort th elements.

**Comment by kylefox** [comment]
Can you please provide a publicly-viewable test case (ex: [CodePen](http://codepen.io/)). Thanks.

**Comment by SoLoGHoST** [comment]
You can see this by clicking on the Zip code Column multiple times on this fiddle here:  http://jsfiddle.net/rjkkv3wv/

**Comment by SoLoGHoST** [comment]
I just copied your js file code in there, into the js box, though it doesn't matter how it's inserted, js, or file.  The problem still occurs.  It is not sorting the tr elements properly everytime.

**Comment by kelesi** [comment]
@SoLoGHoST Your source HTML in the jsfiddle already contains the &#8203;
```html					
<td class="zipcode column-zipcode" data-sort-value="&#8203;07439">
    &#8203;07439<input type="hidden" name="zip[]" value="&#8203;07439">
</td>
```

**Comment by SoLoGHoST** [comment]
Awww, I see, this must be an issue with my code somewhere.  Thanks for pointing that out!

**Comment by kylefox** [comment]
Cool, thanks @kelesi !

**Comment by SoLoGHoST** [comment]
Sorry, this is still an issue, you can now see it here:  http://jsfiddle.net/rjkkv3wv/3/

**Comment by SoLoGHoST** [comment]
Almost always there is a problem with 18106 zip code.

**Comment by SoLoGHoST** [comment]
The HTML is just fine by default, but the `&#8203;` gets inputted into the data-sort-value randomly here, during sorting of the table, clicking on <th> elements.  The jsfiddle I had posted earlier, was the html from the inspector, not the actual source code of my html.  The Chrome inspector gave me that, but this was because I was already sorting the table prior to inspecting the table.  The new jsfiddle that I posted above, now is the correct html output directly from the HTML Source.  So that should be better now at identifying the problem.  Sorry guys.

**Comment by SoLoGHoST** [comment]
Problem fixed, this is not an issue with this plugin.  Sorry, problem was occuring due to a zero-width-space \u200b being returned from the PHP that was responsible for echoing out the zipcodes.  I fixed this and this plugin is AWESOME bytheway!  Thank you for this AWESOME plugin!  Love it!

**Comment by kylefox** [comment]
:+1:
