### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by larsbo** [kylefox/jquery-tablesort#26]
Hi, I wonder if a pagination option could be integrated without making the plugin much larger.
If you think that does't fit into this plugin are there any pagination solutions available that work with this plugin?
There is datatables.net but that's way to much additional not needed functionality (and has it's own sorting).

**Comment by kylefox** [comment]
Hi there — pagination is outside the scope of this plugin.

However, it _would_ be nice to know about other pagination plugins that work well with jquery-tablesort. Unfortunately I don't really know of any great jQuery pagination plugins for tables.

If you (or anyone else) comes across a jQuery table pagination plugin that plays nicely with jquery-tablesort, please post a comment and I'll link to it in the README. Thanks!
