### ISSUE TITLE
Only sorts on first click

### ISSUE THREAD

**Issue by billyrennekamp** [kylefox/jquery-tablesort#28]
The first time it is triggered it works, subsequent times the ascending and descending classes work, debug reads successfully, but the rows are not actually reordered. I've added explicit sortBy and logged the values being generated to make sure they all are correct, but still no re-rder afer the initial click.

**Comment by billyrennekamp** [comment]
it seems after sort the <tr> elements are removed from the <tbody> and placed below in the table...

**Comment by kylefox** [comment]
Sounds odd — can you link to an example that demonstrates the issue? Cheers.

**Comment by SuperPuppet** [comment]
some problem occur , only sorts in first click.

**Comment by SuperPuppet** [comment]
you can check http://semantic-ui.com/collections/table.html#sortable
it uses 0.0.1 version , but if you replace with the latest version , It just sorts in first click.

**Comment by kylefox** [comment]
Fixed in [v0.0.11](https://github.com/kylefox/jquery-tablesort/tree/v0.0.11).
