### ISSUE TITLE
Exclude some column from being sorted.

### ISSUE THREAD

**Issue by kasimbadami** [kylefox/jquery-tablesort#6]
Is there any way I can specify column that should not be sorted ?

**Comment by Gelbotron** [comment]
Quite old but may be useful. I just set the class of the column to "column-unsortable" and did the following:
<pre>
$('table').tablesort();
$(".column-unsortable").unbind();
</pre>

**Comment by kylefox** [comment]
This functionality is now included in jquery-tablesort (0.0.3).

To prevent a column from being sortable, just add the `no-sort` class to your `th`:

```html
<th class="no-sort">Photo</th>
```

Try the "Photo" column in the demo:
https://dl.dropboxusercontent.com/u/780754/tablesort/index.html
